# Generated by Django 4.1 on 2022-09-01 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def populate_categories(apps, schema_editor):
    names = [("Indumentaria", "#E53935"), ("Accesorios", "#D81B60"), ("Gastronomia", "#8E24AA"), ("Hogar", "#3949AB"), ("Vivero", "#43A047"), ("Otros", "#FB8C00")]                               
    EntrepreneurCategory = apps.get_model('entrepreneurs', 'EntrepreneurCategory')
    for name, color in names:
        obj = EntrepreneurCategory(description=name, color=color)
        obj.save()

def populate_status(apps, schema_editor):
    names = [("Pendiente", "#1E88E5"), ("Activo", "#43A047"), ("Rechazado", "#E53935"), ("Eliminado", "#9E9E9E")]                               
    EntrepreneurStatus = apps.get_model('entrepreneurs', 'EntrepreneurStatus')
    for name, color in names:
        obj = EntrepreneurStatus(description=name, color=color)
        obj.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('color', models.CharField(default='#17a2b8', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='EntrepreneurStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('color', models.CharField(default='#17a2b8', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrepreneurship_name', models.CharField(max_length=100)),
                ('entrepreneurship_email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_profile', models.ImageField(default='default.jpg', upload_to='images/entrepreneur_profile_pics')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrepreneurs.entrepreneurcategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrepreneurs.entrepreneurstatus')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

        migrations.RunPython(populate_categories, migrations.RunPython.noop),
        migrations.RunPython(populate_status, migrations.RunPython.noop),
    ]
