# Generated by Django 4.1 on 2022-08-31 11:07

from django.db import migrations, models
import django.db.models.deletion

def populate_categories(apps, schema_editor):
    names = ["Indumentaria", "Accesorios", "Gastronomia", "Hogar", "Vivero", "Otros"]                               
    EntrepreneurCategory = apps.get_model('entrepreneurs', 'EntrepreneurCategory')
    for name in names:
        obj = EntrepreneurCategory(description=name)
        obj.save()

def populate_status(apps, schema_editor):
    names = ["Pendiente", "Activo", "Rechazado", "Eliminado"]                               
    EntrepreneurStatus = apps.get_model('entrepreneurs', 'EntrepreneurStatus')
    for name in names:
        obj = EntrepreneurStatus(description=name)
        obj.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EntrepreneurStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrepreneurship_name', models.CharField(max_length=100)),
                ('entrepreneurship_email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrepreneurs.entrepreneurcategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrepreneurs.entrepreneurstatus')),
            ],
        ),

        migrations.RunPython(populate_categories),
        migrations.RunPython(populate_status),
    ]
