# Generated by Django 4.1 on 2022-08-27 20:59

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_client_user_role_clientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('entrepreneur', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EntrepreneurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrepreneur_id', models.IntegerField(blank=True, null=True)),
                ('entrepreneurship_name', models.CharField(max_length=100)),
                ('entrepreneurship_email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
