# Generated by Django 4.1 on 2022-09-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entrepreneurs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrepreneur",
            name="image_profile",
            field=models.ImageField(
                default="images/default.jpg",
                upload_to="images/entrepreneur_profile_pics",
            ),
        ),
    ]
