# Generated by Django 4.1 on 2022-09-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='image_profile',
            field=models.ImageField(default='default.jpg', upload_to='images/entrepreneur_profile_pics'),
        ),
    ]
