# Generated by Django 4.1 on 2022-09-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entrepreneurs", "0002_alter_entrepreneur_image_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrepreneur",
            name="number_of_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
