# Generated by Django 4.1 on 2022-10-15 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entrepreneurs", "0004_alter_entrepreneur_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrepreneur",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="entrepreneurs.entrepreneurcategory",
                verbose_name="Categoría del Emprendimiento",
            ),
        ),
        migrations.AlterField(
            model_name="entrepreneur",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="entrepreneurs.entrepreneurstatus",
                verbose_name="Estado del Emprendimiento",
            ),
        ),
    ]
