# Generated by Django 4.1 on 2022-09-19 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0005_event_datetime_of_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="content",
            field=models.TextField(verbose_name="Contenido del evento"),
        ),
        migrations.AlterField(
            model_name="event",
            name="cost_of_entry",
            field=models.IntegerField(verbose_name="Costo de la entrada"),
        ),
        migrations.AlterField(
            model_name="event",
            name="datetime_of_event",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                verbose_name="Fecha de Realización del evento",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="direction",
            field=models.TextField(verbose_name="Dirección del evento"),
        ),
        migrations.AlterField(
            model_name="event",
            name="image_profile",
            field=models.ImageField(
                default="images/default.jpg",
                upload_to="images/event_pics",
                verbose_name="Imagen de Perfil del evento",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Título del evento"),
        ),
    ]
